### ISSUE TITLE
[TODO] Proper paragraph text for Organizational Design section of Services page

### ISSUE THREAD

**Issue by ZhangJieSong** [GCGT/TemboGroup#39]
We design, repair and restructure organizations and programs to support and maximize their social impact. We build foundations, non-profits and corporate sustainability programs from the ground up. We create structure where little exists — taking fragmented efforts, and bringing focus, rigor, strategy and structure so organizations can be more efficient with their resources. We realign incentives and create institutional mechanisms to foster greater collaboration. Services include:

// The section name is misspelled. Should be 'Organizational Design'
// The bottom text is fine

**Comment by vxsm26** [comment]
Done
