### ISSUE TITLE
[TODO] Proper text for Partnerships & Coalitions page in the Services section

### ISSUE THREAD

**Issue by ZhangJieSong** [GCGT/TemboGroup#41]
Solving the world's most intractable societal ails cannot be done in isolation, and while partnerships used to be a novel idea, today they are an operational requirement. At Tembo, we have built a proprietary system for analyzing, mapping, engaging and managing partnerships and coalitions. For each of our clients, we ensure your work is not duplicating efforts, but rather helping to lift up our collective efforts for optimal impact and return on investment. Services include:

// _Bottom text is fine_

**Comment by vxsm26** [comment]
Done
