### ISSUE TITLE
[TODO] Proper text for Movement Making page in the Services section

### ISSUE THREAD

**Issue by ZhangJieSong** [GCGT/TemboGroup#42]
The scale of challenges humanity faces requires collective action, and often radical shifts in culture and behaviors. Instigating this change means sparking real movements, which can be intentionally built, but must be collectively adopted. It means building narratives that permeate popular media, tied to specific policy and behavior changes. We work with clients to design, build and catalyze movements. Services include:

// _Bottom text is fine_

**Comment by vxsm26** [comment]
Done
