### ISSUE TITLE
[TODO] Proper text for Content & Thought Leadership section of Services page

### ISSUE THREAD

**Issue by ZhangJieSong** [GCGT/TemboGroup#43]
Leading in the 21st century requires that we catalyze conversations, shape debates, and create the frames through which people digest information. At Tembo, we work closely with clients to articulate their points of view, and translate their perspectives into influential content, and distribute that content across the most relevant channels. Services include:

// _bottom text is fine_

**Comment by vxsm26** [comment]
Done
